### PR TITLE
Remote Control: Joy to Twist Conversion for /cmd_vel

### LINKED ISSUE #28: Remote Control
We need to be able to control the sub over ethernet. The [joy package](https://index.ros.org/p/joy/github-ros-drivers-joystick_drivers/#humble) should be a useful tool for reading joystick commands. The joystick commands will need to be translated to [Twist messages](http://docs.ros.org/en/noetic/api/geometry_msgs/html/msg/Twist.html) and published to `/cmd_vel` to be used by the motor controller. The code should be implemented in `pontus_controller`, and there should be a launch file (e.g. `rc.launch.py`) in `pontus_controller` which allows us to start remote control.

### PR DESCRIPTION
**Pull request by chxtio**
Closes #28 

- Couldn't build b/c of pontus_sensors package, had to run `colcon build --packages-select pontus_controller`

To launch, run `ros2 launch pontus_controller rc.launch.py`
- If you get error: "can't copy 'launch/__pycache__': doesn't exist or not a regular file",  delete ‘__pycache__’ folder

### CODE REVIEW

**Comment by mroglan** [comment]
The parameter file wasn't being passed into the node before. I also created separate `sim` and `auv` directories so that we can have different parameters if necessary between simulation and the auv. You can toggle which parameters are used by passing in `auv:=auv` or `auv:=sim` to the launch command (it defaults to `auv` if none is passed in).

I'll merge this once we test it with the joysticks in the lab. Great work!

**Comment by chxtio** [comment]
When I use `parameters=[params]` instead of `parameters=[{'ros__parameters': params}]`, I get this warning:
> [WARNING] [launch_ros.actions.node]: Parameter file path is not a file: ~/mrg/dev_ws/install/pontus_controller/share/pontus_controllerconfigauvjoystick.yaml

Also, how would I run the simulation, would I need gazebo garden?

**Comment by mroglan** [comment]
Fixed the config issue. The parameters should now be getting passed in.

Regarding the simulation, yes you will gazebo garden to run. You can start the simulation with `ros2 launch pontus_bringup odom_simulation.launch.py`. In simulation, it would be good if we could drive the sub around with `ros2 launch pontus_controller rc.launch.py auv:=sim`, so test that functionality if you're able to get the simulation running.

**Comment by chxtio** [comment]
Do I need to launch anything else? Because it seems like nothing was publishing to /cmd_accel

**Comment by mroglan** [comment]
You should only need to publish to `/cmd_vel` for the sub to move. For example, publishing a linear cmd vel of x=1.0 will make the sub move forward in simulation. I can meet over Teams to discuss as well.

**Comment by chachmu** [comment]
Out of curiosity does teleop_twist_joy support 3d movement? The code makes it look like it is only doing forward/backwards and yaw.

**Comment by mroglan** [comment]
We added the ability to move up and down in the lab today. It required mapping an extra axis on the controller to the z component of the linear velocity.

**Review by mroglan — APPROVED** [review]

**Comment by chxtio** [comment]
My bad for going AFK, but a few days ago I had already built using `colcon build --packages-skip pontus_sensors` and the velocity controller node was receiving messages on `cmd_vel` but not `'/pontus/odometry'`

I'll try it again now and if it still doesn't work on my end I'll go on Teams

**Pull request merged**
