### PR TITLE
Basic Pool Environment Creation

### PR DESCRIPTION
**Pull request by jaiden-lee**
- Added empty pool: 4 walls, floor, 9 lane markers
- Pool dimensions: 50m x 25m x 3m
- Added light source to allow for shadows
- Wall and floor colors = off white/grey
- Lane markers: navy blue

### CODE REVIEW

**Comment by mroglan** [comment]
I've added Matthew as a reviewer as well since he is most familiar with the simulation.

**Review by mroglan — CHANGES_REQUESTED** [review]
I think `underwater.sdf` was just purely expiremental. If so, can we delete it?

**Comment by jaiden-lee** [comment]
> I think `underwater.sdf` was just purely expiremental. If so, can we delete it?

Yeah I forgot to delete it my bad

**Review by mroglan — APPROVED** [review]
Collision is working. This should be a good platform for us to build on. If @chachmu approves, this should be good to merge.

**Review by chachmu — APPROVED** [review]
Looks great :+1:

**Pull request merged**
